version: 1
disable_existing_loggers: false
loggers:
    '':
       level: INFO
       handlers: [console, file]
    simple:
       level: INFO
       handlers: [simpleconsole]
       propagate: no
handlers:
    console:
        class:     logging.StreamHandler
        level:     INFO
        formatter: long
        stream:    ext://sys.stdout
    file:
        class:     logging.FileHandler
        level:     INFO
        formatter: long
        filename:  log.txt
        mode:      w
    simpleconsole:
        class:     logging.StreamHandler
        level:     INFO
        formatter: short
        stream:    ext://sys.stdout
formatters:
    long:
        format:  '[%(name)s:%(levelname)s]:%(message)s\n(%(pathname)s\%(lineno)s, time:%(asctime)s)\n'
        datefmt: '%H:%M'
    short:
        format:  '[%(levelname)s]:%(message)s'